[build-system]

requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "pywris"
version = "0.0.1"
keywords = ["water", "India", "WRIS"]

[project.optional-dependencies]

[project.urls]

[project.script]

[project.gui-scripts]

[project.entry-points]